---
config: vet_50a_all_text
my_text_model: james-burton/vet_50a
ds_name: james-burton/vet_month_1_all_text
text_model_base: SAVSNET/PetBERT_pretrained
model_type: all_text
ord_ds_name: james-burton/vet_month_1_ordinal
text_model_code: pbert_pt

---
config: vet_59a_stack
my_text_model: james-burton/vet_59a
ds_name: james-burton/vet_month_1_ordinal
text_model_base: SAVSNET/PetBERT_pretrained
model_type: stack
ord_ds_name: james-burton/vet_month_1_ordinal

---
config: vet_50a_baseline
my_text_model: james-burton/vet_50a
ds_name: james-burton/vet_month_1_all_text
text_model_base: SAVSNET/PetBERT_pretrained
model_type: all_text
ord_ds_name: james-burton/vet_month_1_ordinal
---
config: vet_59a_ensemble_50
my_text_model: james-burton/vet_59a
ds_name: james-burton/vet_month_1_ordinal
text_model_base: SAVSNET/PetBERT_pretrained
model_type: ensemble_50
ord_ds_name: james-burton/vet_month_1_ordinal

---
config: vet_59b_stack
my_text_model: james-burton/vet_59b
ds_name: james-burton/vet_month_1b_ordinal
text_model_base: SAVSNET/PetBERT_pretrained
model_type: stack
ord_ds_name: james-burton/vet_month_1b_ordinal
---
config: vet_50b_all_text
my_text_model: james-burton/vet_50b
ds_name: james-burton/vet_month_1b_all_text
text_model_base: SAVSNET/PetBERT_pretrained
model_type: all_text
ord_ds_name: james-burton/vet_month_1b_ordinal
---
config: vet_50b_baseline
my_text_model: james-burton/vet_50b
ds_name: james-burton/vet_month_1b_all_text
text_model_base: SAVSNET/PetBERT_pretrained
model_type: all_text
ord_ds_name: james-burton/vet_month_1b_ordinal
---
config: vet_59b_ensemble_50
my_text_model: james-burton/vet_59b
ds_name: james-burton/vet_month_1b_ordinal
text_model_base: SAVSNET/PetBERT_pretrained
model_type: ensemble_50
ord_ds_name: james-burton/vet_month_1b_ordinal
---
config: vet_59b_ensemble_25
my_text_model: james-burton/vet_59b
ds_name: james-burton/vet_month_1b_ordinal
text_model_base: SAVSNET/PetBERT_pretrained
model_type: ensemble_25
ord_ds_name: james-burton/vet_month_1b_ordinal
---
config: vet_59b_ensemble_75
my_text_model: james-burton/vet_59b
ds_name: james-burton/vet_month_1b_ordinal
text_model_base: SAVSNET/PetBERT_pretrained
model_type: ensemble_75
ord_ds_name: james-burton/vet_month_1b_ordinal
---
config: vet_10b_all_text
my_text_model: james-burton/vet_10b
ds_name: james-burton/vet_month_1b_all_text
text_model_base: bert-base-uncased
model_type: all_text
ord_ds_name: james-burton/vet_month_1b_ordinal
---
config: vet_10b_baseline
my_text_model: james-burton/vet_50b
ds_name: james-burton/vet_month_1b_all_text
text_model_base: bert-base-uncased
model_type: all_text
ord_ds_name: james-burton/vet_month_1b_ordinal
---
config: vet_19b_stack
my_text_model: james-burton/vet_19b
ds_name: james-burton/vet_month_1b_ordinal
text_model_base: bert-base-uncased
model_type: stack
ord_ds_name: james-burton/vet_month_1b_ordinal
---
config: vet_19b_ensemble_50
my_text_model: james-burton/vet_59b
ds_name: james-burton/vet_month_1b_ordinal
text_model_base: bert-base-uncased
model_type: ensemble_50
ord_ds_name: james-burton/vet_month_1b_ordinal
---
config: vet_19b_ensemble_25
my_text_model: james-burton/vet_59b
ds_name: james-burton/vet_month_1b_ordinal
text_model_base: bert-base-uncased
model_type: ensemble_25
ord_ds_name: james-burton/vet_month_1b_ordinal
---
config: vet_19b_ensemble_75
my_text_model: james-burton/vet_59b
ds_name: james-burton/vet_month_1b_ordinal
text_model_base: bert-base-uncased
model_type: ensemble_75
ord_ds_name: james-burton/vet_month_1b_ordinal

### For c, changed dataset such that removed id cols
---
config: vet_59c_stack
my_text_model: james-burton/vet_59c
ds_name: james-burton/vet_month_1c_ordinal
text_model_base: SAVSNET/PetBERT_pretrained
model_type: stack
ord_ds_name: james-burton/vet_month_1c_ordinal
text_cols:
  - breed
  - region
  - record
---
config: vet_50c_all_text
my_text_model: james-burton/vet_50c
ds_name: james-burton/vet_month_1c_all_text
text_model_base: SAVSNET/PetBERT_pretrained
model_type: all_text
ord_ds_name: james-burton/vet_month_1c_ordinal
text_cols:
  - breed
  - region
  - record
---
config: vet_50c_baseline
my_text_model: james-burton/vet_50c
ds_name: james-burton/vet_month_1c_all_text
text_model_base: SAVSNET/PetBERT_pretrained
model_type: all_text
ord_ds_name: james-burton/vet_month_1c_ordinal
text_cols:
  - breed
  - region
  - record
---
config: vet_59c_ensemble_50
my_text_model: james-burton/vet_59c
ds_name: james-burton/vet_month_1c_ordinal
text_model_base: SAVSNET/PetBERT_pretrained
model_type: ensemble_50
ord_ds_name: james-burton/vet_month_1c_ordinal
text_cols:
  - breed
  - region
  - record
---
config: vet_59c_ensemble_25
my_text_model: james-burton/vet_59c
ds_name: james-burton/vet_month_1c_ordinal
text_model_base: SAVSNET/PetBERT_pretrained
model_type: ensemble_25
ord_ds_name: james-burton/vet_month_1c_ordinal
text_cols:
  - breed
  - region
  - record
---
config: vet_59c_ensemble_75
my_text_model: james-burton/vet_59c
ds_name: james-burton/vet_month_1c_ordinal
text_model_base: SAVSNET/PetBERT_pretrained
model_type: ensemble_75
ord_ds_name: james-burton/vet_month_1c_ordinal
text_cols:
  - breed
  - region
  - record
---
config: vet_10c_all_text
my_text_model: james-burton/vet_10c
ds_name: james-burton/vet_month_1c_all_text
text_model_base: bert-base-uncased
model_type: all_text
ord_ds_name: james-burton/vet_month_1c_ordinal
text_cols:
  - breed
  - region
  - record
---
config: vet_10c_baseline
my_text_model: james-burton/vet_10c
ds_name: james-burton/vet_month_1c_all_text
text_model_base: bert-base-uncased
model_type: all_text
ord_ds_name: james-burton/vet_month_1c_ordinal
text_cols:
  - breed
  - region
  - record
---
config: vet_19c_ensemble_50
my_text_model: james-burton/vet_19c
ds_name: james-burton/vet_month_1c_ordinal
text_model_base: bert-base-uncased
model_type: ensemble_50
ord_ds_name: james-burton/vet_month_1c_ordinal
text_cols:
  - breed
  - region
  - record
---
config: vet_19c_ensemble_25
my_text_model: james-burton/vet_19c
ds_name: james-burton/vet_month_1c_ordinal
text_model_base: bert-base-uncased
model_type: ensemble_25
ord_ds_name: james-burton/vet_month_1c_ordinal
text_cols:
  - breed
  - region
  - record
---
config: vet_19c_ensemble_75
my_text_model: james-burton/vet_19c
ds_name: james-burton/vet_month_1c_ordinal
text_model_base: bert-base-uncased
model_type: ensemble_75
ord_ds_name: james-burton/vet_month_1c_ordinal
text_cols:
  - breed
  - region
  - record
---
config: vet_19c_stack
my_text_model: james-burton/vet_19c
ds_name: james-burton/vet_month_1c_ordinal
text_model_base: bert-base-uncased
model_type: stack
ord_ds_name: james-burton/vet_month_1c_ordinal
text_cols:
  - breed
  - region
  - record
