# Key
#

--- #TESTING
config: testing
fast_dev_run: true

---
config: text_col_only
fast_dev_run: false
batch_size: 32
ds_name: james-burton/vet_month_1_ordinal

---
config: all_text
fast_dev_run: false
batch_size: 32
ds_name: james-burton/vet_month_1_all_text
